/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import db.DataManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Usuario;
import modelTM.TMUsuario;

/**
 *
 * @author cristobalO.O
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    
    private DataManager dataManager;
    
    public App() {
        initComponents();
        setConfig();
        setConfigSize();
        
        box_Estado_Ingresa_Nuevo_Trabajador.removeAllItems();
        box_Estado_Ingresa_Nuevo_Trabajador.addItem("Activo");
        box_Estado_Ingresa_Nuevo_Trabajador.addItem("Inactivo");
        
        this.dataManager = new DataManager();
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaTrabajadores = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txt_listaTrabajadores_buscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tm_lista_Trabajadores = new javax.swing.JTable();
        btn_listaTrabajadores_usuarios = new javax.swing.JButton();
        btn_listaTrabajadores_Accesos = new javax.swing.JButton();
        btn_listaTrabajadores_reportes = new javax.swing.JButton();
        btn_listaTrabajadores_salir = new javax.swing.JButton();
        IngresarNuevoTrabajador = new javax.swing.JFrame();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        Text_ID_Ingresa_Nuevo_Trabajador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Text_Rut_Ingresa_Nuevo_Trabajador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Text_Nombre_Ingresa_Nuevo_Trabajador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Text_Apellido_Ingresa_Nuevo_Trabajador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Text_Correo_Ingresa_Nuevo_Trabajador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Text_Contraseña_Ingresa_Nuevo_Trabajador = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Text_Rol_Ingresa_Nuevo_Trabajador = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        box_Estado_Ingresa_Nuevo_Trabajador = new javax.swing.JComboBox<>();
        btn_Guardar_Ingresar_Nuevo_Trabajador = new javax.swing.JButton();
        btn_lista_Trabajadores_usuarios1 = new javax.swing.JButton();
        btn_lista_Trabajadores_Accesos1 = new javax.swing.JButton();
        btn_listaTrabajadores_reportes1 = new javax.swing.JButton();
        btn_lista_Trabajadores_salir = new javax.swing.JButton();
        RegistroAcceso = new javax.swing.JFrame();
        colores = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txt_login_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_login_clave = new javax.swing.JTextField();
        btn_Login_ingresar = new javax.swing.JButton();

        jPanel9.setBackground(new java.awt.Color(68, 71, 77));

        jPanel10.setBackground(new java.awt.Color(135, 124, 115));

        jPanel11.setBackground(new java.awt.Color(68, 71, 77));

        txt_listaTrabajadores_buscar.setBackground(new java.awt.Color(213, 208, 196));
        txt_listaTrabajadores_buscar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txt_listaTrabajadores_buscar.setText("Buscar........................");

        jButton1.setBackground(new java.awt.Color(156, 165, 177));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(156, 165, 177));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.setToolTipText("");

        jPanel12.setBackground(new java.awt.Color(213, 208, 196));

        jScrollPane1.setBackground(new java.awt.Color(213, 208, 196));

        tm_lista_Trabajadores.setBackground(new java.awt.Color(213, 208, 196));
        tm_lista_Trabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tm_lista_Trabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tm_lista_TrabajadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tm_lista_Trabajadores);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txt_listaTrabajadores_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 92, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGap(17, 17, 17))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_listaTrabajadores_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btn_listaTrabajadores_usuarios.setBackground(new java.awt.Color(156, 165, 177));
        btn_listaTrabajadores_usuarios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_listaTrabajadores_usuarios.setText("Usuarios");
        btn_listaTrabajadores_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listaTrabajadores_usuariosActionPerformed(evt);
            }
        });

        btn_listaTrabajadores_Accesos.setBackground(new java.awt.Color(156, 165, 177));
        btn_listaTrabajadores_Accesos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_listaTrabajadores_Accesos.setText("Accesos");
        btn_listaTrabajadores_Accesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listaTrabajadores_AccesosActionPerformed(evt);
            }
        });

        btn_listaTrabajadores_reportes.setBackground(new java.awt.Color(156, 165, 177));
        btn_listaTrabajadores_reportes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_listaTrabajadores_reportes.setText("Reportes");
        btn_listaTrabajadores_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listaTrabajadores_reportesActionPerformed(evt);
            }
        });

        btn_listaTrabajadores_salir.setBackground(new java.awt.Color(156, 165, 177));
        btn_listaTrabajadores_salir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_listaTrabajadores_salir.setText("Salir");
        btn_listaTrabajadores_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listaTrabajadores_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_listaTrabajadores_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_listaTrabajadores_Accesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_listaTrabajadores_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_listaTrabajadores_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btn_listaTrabajadores_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_listaTrabajadores_Accesos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_listaTrabajadores_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_listaTrabajadores_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ListaTrabajadoresLayout = new javax.swing.GroupLayout(ListaTrabajadores.getContentPane());
        ListaTrabajadores.getContentPane().setLayout(ListaTrabajadoresLayout);
        ListaTrabajadoresLayout.setHorizontalGroup(
            ListaTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
            .addGroup(ListaTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListaTrabajadoresLayout.setVerticalGroup(
            ListaTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
            .addGroup(ListaTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaTrabajadoresLayout.createSequentialGroup()
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel13.setBackground(new java.awt.Color(68, 71, 77));

        jPanel14.setBackground(new java.awt.Color(135, 124, 115));

        jPanel15.setBackground(new java.awt.Color(68, 71, 77));

        jPanel16.setBackground(new java.awt.Color(156, 165, 177));

        Text_ID_Ingresa_Nuevo_Trabajador.setText("jTextField1");
        Text_ID_Ingresa_Nuevo_Trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_ID_Ingresa_Nuevo_TrabajadorActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        jLabel5.setText("Rut");

        Text_Rut_Ingresa_Nuevo_Trabajador.setText("jTextField2");

        jLabel6.setText("Nombre");

        Text_Nombre_Ingresa_Nuevo_Trabajador.setText("jTextField3");

        jLabel7.setText("Apellido");

        Text_Apellido_Ingresa_Nuevo_Trabajador.setText("jTextField4");

        jLabel8.setText("Correo");

        Text_Correo_Ingresa_Nuevo_Trabajador.setText("jTextField5");

        jLabel9.setText("Contraseña");

        Text_Contraseña_Ingresa_Nuevo_Trabajador.setText("jTextField6");

        jLabel10.setText("Rol");

        Text_Rol_Ingresa_Nuevo_Trabajador.setText("jTextField7");

        jLabel11.setText("Estado");

        box_Estado_Ingresa_Nuevo_Trabajador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box_Estado_Ingresa_Nuevo_Trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Estado_Ingresa_Nuevo_TrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(Text_ID_Ingresa_Nuevo_Trabajador, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addComponent(Text_Rut_Ingresa_Nuevo_Trabajador)
                    .addComponent(Text_Nombre_Ingresa_Nuevo_Trabajador)
                    .addComponent(Text_Apellido_Ingresa_Nuevo_Trabajador)
                    .addComponent(Text_Correo_Ingresa_Nuevo_Trabajador)
                    .addComponent(Text_Contraseña_Ingresa_Nuevo_Trabajador)
                    .addComponent(Text_Rol_Ingresa_Nuevo_Trabajador)
                    .addComponent(box_Estado_Ingresa_Nuevo_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_ID_Ingresa_Nuevo_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Rut_Ingresa_Nuevo_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Nombre_Ingresa_Nuevo_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Apellido_Ingresa_Nuevo_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Correo_Ingresa_Nuevo_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Contraseña_Ingresa_Nuevo_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Rol_Ingresa_Nuevo_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box_Estado_Ingresa_Nuevo_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btn_Guardar_Ingresar_Nuevo_Trabajador.setBackground(new java.awt.Color(156, 165, 177));
        btn_Guardar_Ingresar_Nuevo_Trabajador.setText("Guardar");
        btn_Guardar_Ingresar_Nuevo_Trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Guardar_Ingresar_Nuevo_TrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Guardar_Ingresar_Nuevo_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Guardar_Ingresar_Nuevo_Trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        btn_lista_Trabajadores_usuarios1.setBackground(new java.awt.Color(156, 165, 177));
        btn_lista_Trabajadores_usuarios1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_lista_Trabajadores_usuarios1.setText("Usuarios");
        btn_lista_Trabajadores_usuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lista_Trabajadores_usuarios1ActionPerformed(evt);
            }
        });

        btn_lista_Trabajadores_Accesos1.setBackground(new java.awt.Color(156, 165, 177));
        btn_lista_Trabajadores_Accesos1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_lista_Trabajadores_Accesos1.setText("Accesos");
        btn_lista_Trabajadores_Accesos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lista_Trabajadores_Accesos1ActionPerformed(evt);
            }
        });

        btn_listaTrabajadores_reportes1.setBackground(new java.awt.Color(156, 165, 177));
        btn_listaTrabajadores_reportes1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_listaTrabajadores_reportes1.setText("Reportes");
        btn_listaTrabajadores_reportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listaTrabajadores_reportes1ActionPerformed(evt);
            }
        });

        btn_lista_Trabajadores_salir.setBackground(new java.awt.Color(156, 165, 177));
        btn_lista_Trabajadores_salir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_lista_Trabajadores_salir.setText("Salir");
        btn_lista_Trabajadores_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lista_Trabajadores_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_lista_Trabajadores_usuarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_lista_Trabajadores_Accesos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_listaTrabajadores_reportes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_lista_Trabajadores_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btn_lista_Trabajadores_usuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_lista_Trabajadores_Accesos1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_listaTrabajadores_reportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_lista_Trabajadores_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout IngresarNuevoTrabajadorLayout = new javax.swing.GroupLayout(IngresarNuevoTrabajador.getContentPane());
        IngresarNuevoTrabajador.getContentPane().setLayout(IngresarNuevoTrabajadorLayout);
        IngresarNuevoTrabajadorLayout.setHorizontalGroup(
            IngresarNuevoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(IngresarNuevoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IngresarNuevoTrabajadorLayout.setVerticalGroup(
            IngresarNuevoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
            .addGroup(IngresarNuevoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngresarNuevoTrabajadorLayout.createSequentialGroup()
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout RegistroAccesoLayout = new javax.swing.GroupLayout(RegistroAcceso.getContentPane());
        RegistroAcceso.getContentPane().setLayout(RegistroAccesoLayout);
        RegistroAccesoLayout.setHorizontalGroup(
            RegistroAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        RegistroAccesoLayout.setVerticalGroup(
            RegistroAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(68, 71, 77));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(156, 165, 177));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(213, 208, 196));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(135, 124, 115));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout coloresLayout = new javax.swing.GroupLayout(colores.getContentPane());
        colores.getContentPane().setLayout(coloresLayout);
        coloresLayout.setHorizontalGroup(
            coloresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coloresLayout.createSequentialGroup()
                .addGroup(coloresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        coloresLayout.setVerticalGroup(
            coloresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coloresLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(68, 71, 77));

        jPanel6.setBackground(new java.awt.Color(135, 124, 115));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(213, 208, 196));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Login");

        jPanel8.setBackground(new java.awt.Color(156, 165, 177));

        txt_login_usuario.setBackground(new java.awt.Color(213, 208, 196));
        txt_login_usuario.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txt_login_usuario.setText("Ingrese su usuario");
        txt_login_usuario.setToolTipText("txt_login_usuario");
        txt_login_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_usuarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Clave");

        text_login_clave.setBackground(new java.awt.Color(213, 208, 196));
        text_login_clave.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        text_login_clave.setText("ingrese su clave");
        text_login_clave.setToolTipText("text_login_clave");
        text_login_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_login_claveActionPerformed(evt);
            }
        });

        btn_Login_ingresar.setBackground(new java.awt.Color(213, 208, 196));
        btn_Login_ingresar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Login_ingresar.setText("Ingresar");
        btn_Login_ingresar.setToolTipText("");
        btn_Login_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Login_ingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(text_login_clave)
                            .addComponent(txt_login_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btn_Login_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_login_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Login_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_login_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_usuarioActionPerformed

    private void text_login_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_login_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_login_claveActionPerformed

    private void btn_Login_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Login_ingresarActionPerformed
        try {
            // TODO add your handling code here:
            ListaTrabajadores.setVisible(true);
            actualizacionUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_Login_ingresarActionPerformed

    private void btn_listaTrabajadores_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaTrabajadores_usuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_listaTrabajadores_usuariosActionPerformed

    private void btn_listaTrabajadores_AccesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaTrabajadores_AccesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_listaTrabajadores_AccesosActionPerformed

    private void btn_listaTrabajadores_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaTrabajadores_reportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_listaTrabajadores_reportesActionPerformed

    private void btn_listaTrabajadores_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaTrabajadores_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_listaTrabajadores_salirActionPerformed

    private void btn_lista_Trabajadores_usuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lista_Trabajadores_usuarios1ActionPerformed
        // TODO add your handling code here:
        ListaTrabajadores.setVisible(true);
    }//GEN-LAST:event_btn_lista_Trabajadores_usuarios1ActionPerformed

    private void btn_lista_Trabajadores_Accesos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lista_Trabajadores_Accesos1ActionPerformed
        // TODO add your handling code here:
        RegistroAcceso.setVisible(true);
    }//GEN-LAST:event_btn_lista_Trabajadores_Accesos1ActionPerformed

    private void btn_listaTrabajadores_reportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaTrabajadores_reportes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_listaTrabajadores_reportes1ActionPerformed

    private void btn_lista_Trabajadores_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lista_Trabajadores_salirActionPerformed
        // TODO add your handling code here:
        ListaTrabajadores.setVisible(true);
    }//GEN-LAST:event_btn_lista_Trabajadores_salirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            resetFormPersonal();
            int ultimaId = dataManager.getDataUsuario().getUltimaId();
            Text_ID_Ingresa_Nuevo_Trabajador.setText(String.valueOf(ultimaId));
            IngresarNuevoTrabajador.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_Guardar_Ingresar_Nuevo_TrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Guardar_Ingresar_Nuevo_TrabajadorActionPerformed
        // TODO add your handling code here:
         try {
            try {
                Usuario u = getDataFormUsuario();
                if (u == null) {
                    JOptionPane.showMessageDialog(this.IngresarNuevoTrabajador, "No se pudo obtener el personal debido a campos vacíos o datos inválidos.");
                    return;
                }

                Usuario existente = dataManager.getDataUsuario().getOne(u.getIdUsuario());
                if (existente != null) {
                    dataManager.getDataUsuario().update(u);
                    JOptionPane.showMessageDialog(this.ListaTrabajadores, "Usuario modificado con éxito.");
                } else {
                    dataManager.getDataUsuario().agregar(u);
                    JOptionPane.showMessageDialog(this.ListaTrabajadores, "Usuario agregado con éxito.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this.ListaTrabajadores, "Hubo un error al procesar la operación.");
            }
            actualizacionUsuario();
            ListaTrabajadores.setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_Guardar_Ingresar_Nuevo_TrabajadorActionPerformed

    private void Text_ID_Ingresa_Nuevo_TrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_ID_Ingresa_Nuevo_TrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_ID_Ingresa_Nuevo_TrabajadorActionPerformed

    private void tm_lista_TrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tm_lista_TrabajadoresMouseClicked
        try {
            // TODO add your handling code here:
            int fila = tm_lista_Trabajadores.rowAtPoint(evt.getPoint());
            int id = (int) tm_lista_Trabajadores.getModel().getValueAt(fila, 0);
            Usuario u = dataManager.getDataUsuario().getOne(id);
            if (u != null) {
                IngresarNuevoTrabajador.setVisible(true);
                Text_ID_Ingresa_Nuevo_Trabajador.setText(String.valueOf(u.getIdUsuario()));
                Text_Rut_Ingresa_Nuevo_Trabajador.setText(u.getRut());
                Text_Nombre_Ingresa_Nuevo_Trabajador.setText(u.getNombre());
                Text_Apellido_Ingresa_Nuevo_Trabajador.setText(u.getApellido());
                Text_Correo_Ingresa_Nuevo_Trabajador.setText(u.getCorreo());
                Text_Contraseña_Ingresa_Nuevo_Trabajador.setText(u.getContraseña());
                Text_Rol_Ingresa_Nuevo_Trabajador.setText(u.getRol());
                box_Estado_Ingresa_Nuevo_Trabajador.setSelectedItem(u.getEstado());

                
            }
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tm_lista_TrabajadoresMouseClicked

    private void box_Estado_Ingresa_Nuevo_TrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Estado_Ingresa_Nuevo_TrabajadorActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_box_Estado_Ingresa_Nuevo_TrabajadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame IngresarNuevoTrabajador;
    private javax.swing.JFrame ListaTrabajadores;
    private javax.swing.JFrame RegistroAcceso;
    private javax.swing.JTextField Text_Apellido_Ingresa_Nuevo_Trabajador;
    private javax.swing.JTextField Text_Contraseña_Ingresa_Nuevo_Trabajador;
    private javax.swing.JTextField Text_Correo_Ingresa_Nuevo_Trabajador;
    private javax.swing.JTextField Text_ID_Ingresa_Nuevo_Trabajador;
    private javax.swing.JTextField Text_Nombre_Ingresa_Nuevo_Trabajador;
    private javax.swing.JTextField Text_Rol_Ingresa_Nuevo_Trabajador;
    private javax.swing.JTextField Text_Rut_Ingresa_Nuevo_Trabajador;
    private javax.swing.JComboBox<String> box_Estado_Ingresa_Nuevo_Trabajador;
    private javax.swing.JButton btn_Guardar_Ingresar_Nuevo_Trabajador;
    private javax.swing.JButton btn_Login_ingresar;
    private javax.swing.JButton btn_listaTrabajadores_Accesos;
    private javax.swing.JButton btn_listaTrabajadores_reportes;
    private javax.swing.JButton btn_listaTrabajadores_reportes1;
    private javax.swing.JButton btn_listaTrabajadores_salir;
    private javax.swing.JButton btn_listaTrabajadores_usuarios;
    private javax.swing.JButton btn_lista_Trabajadores_Accesos1;
    private javax.swing.JButton btn_lista_Trabajadores_salir;
    private javax.swing.JButton btn_lista_Trabajadores_usuarios1;
    private javax.swing.JFrame colores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField text_login_clave;
    private javax.swing.JTable tm_lista_Trabajadores;
    private javax.swing.JTextField txt_listaTrabajadores_buscar;
    private javax.swing.JTextField txt_login_usuario;
    // End of variables declaration//GEN-END:variables
    
    
    private void setConfig() {
        this.setLocationRelativeTo(null);
    }
    
    private void setConfigSize() {
        ListaTrabajadores.pack();  
        ListaTrabajadores.setLocationRelativeTo(null);

        IngresarNuevoTrabajador.pack();
        IngresarNuevoTrabajador.setLocationRelativeTo(null);
        
        int ancho = 800;
        int alto = 820;

        ListaTrabajadores.setSize(ancho, alto);
        IngresarNuevoTrabajador.setSize(ancho, alto);
    }
        
    private void actualizacionUsuario() throws SQLException {
        java.util.List<Usuario> tmuser = dataManager.getDataUsuario().getAll();
        TMUsuario tmUser = new TMUsuario(tmuser);
        tm_lista_Trabajadores.setModel(tmUser);
    }
    private void resetFormPersonal() {
           //app_modicarUsuario_txt_id.setText(String.valueOf(calcularId()));
           Text_ID_Ingresa_Nuevo_Trabajador.setText("");
           Text_Rut_Ingresa_Nuevo_Trabajador.setText("");
           Text_Nombre_Ingresa_Nuevo_Trabajador.setText("");
           Text_Apellido_Ingresa_Nuevo_Trabajador.setText("");
           Text_Correo_Ingresa_Nuevo_Trabajador.setText("");
           Text_Contraseña_Ingresa_Nuevo_Trabajador.setText("");
           Text_Rol_Ingresa_Nuevo_Trabajador.setText("");
       }
    
    private Usuario getDataFormUsuario() {
            Usuario u = new Usuario();

            try {
                String rut = validarCampoVacioPersonal(Text_Rut_Ingresa_Nuevo_Trabajador.getText(), "Rut");
                String nombre = validarCampoVacioPersonal(Text_Nombre_Ingresa_Nuevo_Trabajador.getText(), "Nombre");
                String apellido = validarCampoVacioPersonal(Text_Apellido_Ingresa_Nuevo_Trabajador.getText(), "Apellido");
                String correo = validarCampoVacioPersonal(Text_Correo_Ingresa_Nuevo_Trabajador.getText(), "Correo");
                String contraseña = validarCampoVacioPersonal(Text_Contraseña_Ingresa_Nuevo_Trabajador.getText(), "Contraseña");
                String rol = validarCampoVacioPersonal(Text_Rol_Ingresa_Nuevo_Trabajador.getText(), "Rol");
                String estado = box_Estado_Ingresa_Nuevo_Trabajador.getSelectedItem().toString();
                

                if (rut == null || nombre == null || apellido == null || correo == null || 
                    contraseña == null || rol == null ) {
                    
                    return null;
                }

                u.setIdUsuario(Integer.parseInt(Text_ID_Ingresa_Nuevo_Trabajador.getText()));
                u.setRut(rut);
                u.setNombre(nombre);
                u.setApellido(apellido);
                u.setCorreo(correo);
                u.setContraseña(contraseña);
                u.setRol(rol);
                u.setEstado(estado);

                return u;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error con el id.");
                resetFormPersonal();
                return null;
            }
        }
    
        private String validarCampoVacioPersonal(String texto, String nombreCampo) {
        /**
         * Usa trim() para eliminar los espacios en blanco que se encuentran al
         * final y al inicio del texto. Usa isEmpty() para verificar que no haya
         * espacio vacios.
         *
         */
        if (texto == null || texto.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this.IngresarNuevoTrabajador, "El campo " + nombreCampo + " está vacío.");
            return null;
        }
        return texto.trim();

    }

}
